title: Sisi Kata
description: Blog profesional dengan Jekyll dan GitHub Pages
url: "https://sisikata.github.io"
baseurl: ""
repository: yourusername/sisikata.github.io
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/

author:
  name   : Ahmad Kamarudin
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Menulis cerita, opini, dan gagasan sehari-hari."
  location: Indonesia
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yourusername"

permalink: /:categories/:title/
