title: Sisi Kata
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Artikel, opini, dan catatan harian.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sisikata.github.io" # the base hostname & protocol for your site

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: sunrise
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 5
paginate_path: /page:num/
markdown: kramdown
theme: null

author:
  name: El Naryo
  bio: Menyusun kata menjadi makna.
  location: Indonesia

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
